#!/bin/bash

gsf_write_script_sql()
{
    if [ "${IACT_NAME}" = "Import" ]; then
        gsf_write_script_sql_import
    else
        gsf_script_intro_sql

        echo "BEGIN"
        gsf_sql_proc_body_${IACT_NAME}
        echo "END  \$\$"
    fi
}

gsf_write_script_sql_import()
{
    # Environment values for all import functions:
    local QT_NAME="QT_${GF_TNAME}"
    local IMPORT_PROC_ROOT="{GF_PROC_ROOT}Import_"
    local ID_FIELD_NAME="id_session"
    local -i MAX_NAME_LEN="${#ID_FIELD_NAME}"
    lambda_max_name_len()
    {
        local -i len
        if CB_ROW_IS_PARAM; then
            len="${#CALLBACK_ROW[0]}"
            if [ $len -gt $MAX_NAME_LEN ]; then
                MAX_NAME_LEN=$len
            fi
        fi
    }
    # Scan for longest field name length:
    gsf_callback_prefs_rows "lambda_max_name_len"


    gsf_sql_import_table
    echo
    gsf_sql_import_proc_review
    echo
    gsf_sql_import_proc_abandon
    echo
    gsf_sql_import_proc_accept
}

# gsf_add_params_sql()
# Adds an indented list of stored procedure parameters
# for field prefs that have the Param flag set.
gsf_add_params_sql()
{
    local indent_chars="$1"
    local IFS
    local -t row
    local -i commas=0
    local rowstr
    for rowstr in "${IACT_COL_PREFS[@]}"; do
        IFS="${YSEP}"
        row=( $( echo "${rowstr}" ) )
        if [ "${row[2]}" = "TRUE" ]; then
            if [ $(( commas++ )) -gt 0 ]; then
                echo ","
                echo -n "${indent_chars}"
            fi
            echo -n "${row[0]} ${row[1]}" 
        fi
    done
}

# gsf_add_selects_sql()
# Adds field names to a select statement for fields prefs
# that have the Result flag set.
gsf_add_selects_sql()
{
    local indent_chars="$1"
    local prefix=""

    if [ $# -gt 1 ]; then
        prefix="$2."
    fi

    local IFS
    local -t row
    local -i commas=0
    local rowstr
    for rowstr in "${IACT_COL_PREFS[@]}"; do
        IFS="${YSEP}"
        row=( $( echo "${rowstr}" ) )
        if [ "${row[3]}" = "TRUE" ]; then
            if [ $(( commas++ )) -gt 0 ]; then
                echo ","
                echo -n "${indent_chars}"
            fi
            echo -n "${prefix}${row[0]}" 
        fi
    done
}

gsf_script_intro_sql()
{
    echo "DROP PROCEDURE IF EXISTS ${GF_PROC_ROOT}${IACT_NAME} \$\$"
    local str_create_proc="CREATE PROCEDURE ${GF_PROC_ROOT}${IACT_NAME}("

    echo -n "${str_create_proc}"

    # parameter expansion to replace all characters with a space for
    # aligning all the parameters with the open paren:
    gsf_add_params_sql "${str_create_proc//?/ }"
    echo ")"
}

declare GSF_SELECT_LINE="${gsf_script_indent}SELECT "
declare   GSF_FROM_LINE="${gsf_script_indent}  FROM "
declare    GSF_SET_LINE="${gsf_script_indent}   SET "
declare  GSF_WHERE_LINE="${gsf_script_indent} WHERE "
declare    GSF_AND_LINE="${gsf_script_indent}   AND "


declare GSF_UPDATE_FIELDS_LINE="${gsf_script_indent}       ("
declare GSF_UPDATE_VALUES_LINE="${gsf_script_indent}VALUES ("

declare GSF_SELECT_SPACES="${GSF_SELECT_LINE//?/ }"
declare GSF_UPDATE_SPACES_LINE="${GSF_UPDATE_VALUES_LINE//?/ }"

gsf_sql_proc_body_List()
{
    local prefix="t"
    local -i where_count=0

    lambda()
    {
        if CB_ROW_IS_PARAM; then
            # Line-up where parts under the first part:
            if [ $(( where_count++ )) -gt 0 ]; then
                echo
                echo -n "${GSF_AND_LINE}"
            fi

            local fname="${CALLBACK_ROW[0]}"
            if table_field_is_index "${fname}"; then
                echo -n "(${fname} IS NULL OR ${prefix}.${fname}=${fname})"
            else
                echo -n "${prefix}.${fname}=${fname}"
            fi
        fi
    }

    # Build the query/procedure body:
    echo -n "${GSF_SELECT_LINE}"
    gsf_add_selects_sql "${GSF_SELECT_SPACES}" "${prefix}"
    echo
    echo "${GSF_FROM_LINE}${GF_TNAME} ${prefix}"
    echo -n "${GSF_WHERE_LINE}"
    gsf_callback_prefs_rows "lambda"
    echo ";"
}

gsf_sql_proc_body_Add()
{
    local -i lambda_count=0

    lambda_values()
    {
        if CB_ROW_IS_PARAM; then
            local fname="${CALLBACK_ROW[0]}"
            if [ $(( lambda_count++ )) -gt 0 ]; then
                echo ", "
                echo -n "${GSF_UPDATE_SPACES_LINE}"
            fi
            echo -n "${fname}"
        fi
    }

    echo "${gsf_script_indent}DECLARE newid INT UNSIGNED;"
    echo
    echo "${gsf_script_indent}INSERT INTO ${GF_TNAME}"
    lambda_count=0
    echo -n "${GSF_UPDATE_FIELDS_LINE}"
    gsf_callback_prefs_rows "lambda_values"
    echo ")"
    lambda_count=0
    echo -n "${GSF_UPDATE_VALUES_LINE}"
    gsf_callback_prefs_rows "lambda_values"
    echo ");"
    echo
    echo "${gsf_script_indent}IF ROW_COUNT() > 0 THEN"
    echo "${gsf_script_indent}   SET newid = LAST_INSERT_ID();"
    echo "${gsf_script_indent}   CALL List(newid);"
    echo "${gsf_script_indent}END IF;"
}

gsf_sql_proc_body_Read()
{
    local prefix="t"
    local -i where_count=0

    lambda()
    {
        if CB_ROW_IS_PARAM; then
            # Line-up where parts under the first part:
            if [ $(( where_count++ )) -gt 0 ]; then
                echo
                echo -n "${GSF_AND_LINE}"
            fi

            local fname="${CALLBACK_ROW[0]}"
            echo -n "${prefix}.${fname}=${fname}"
        fi
    }

    # Build the query/procedure body:
    echo -n "${GSF_SELECT_LINE}"
    gsf_add_selects_sql "${GSF_SELECT_SPACES}" "${prefix}"
    echo
    echo "${GSF_FROM_LINE}${GF_TNAME} ${prefix}"
    echo -n "${GSF_WHERE_LINE}"
    gsf_callback_prefs_rows "lambda"
    echo ";"
}

gsf_sql_proc_body_Update()
{
    local prefix="t"
    local -i lambda_count=0

    lambda_set()
    {
        if ! CB_ROW_IS_INDEX -a CB_ROW_IS_PARAM; then
            local fname="${CALLBACK_ROW[0]}"
            if [ $(( lambda_count++ )) -gt 0 ]; then
                echo ","
                echo -n "${GSF_SELECT_SPACES}"
            fi
            echo -n "${prefix}.${fname} = ${fname}"
        fi
    }

    lambda_where()
    {
        if CB_ROW_IS_INDEX -a CB_ROW_IS_PARAM; then
            local fname="${CALLBACK_ROW[0]}"
            if [ $(( lambda_count++ )) -gt 0 ]; then
                echo
                echo -n "${GSF_AND_LINE}"
            fi
            echo -n "${prefix}.${fname} = ${fname}"
        fi
    }

    echo "${gsf_script_indent}UPDATE ${GF_TNAME}"
    echo -n "${GSF_SET_LINE}"
    lambda_count=0
    gsf_callback_prefs_rows "lambda_set"
    echo
    echo -n "${GSF_WHERE_LINE}"
    lambda_count=0
    gsf_callback_prefs_rows "lambda_where"
    echo ";"

    local prikey_name
    prikey_name=$( table_get_primary_key )
    if [ $? -eq 0 ]; then
        echo
        echo "${gsf_script_indent}IF ROW_COUNT() > 0 THEN"
        echo "${gsf_script_indent}   CALL List(${prikey_name});"
        echo "${gsf_script_indent}END IF;"
    fi
}

gsf_sql_proc_body_Delete()
{
    local prefix="t"
    local -i lambda_count=0

    lambda_where()
    {
        if CB_ROW_IS_PARAM; then
            local fname="${CALLBACK_ROW[0]}"
            if [ $(( lambda_count++ )) -gt 0 ]; then
                echo
                echo -n "${GSF_AND_LINE}"
            fi
            echo -n "${prefix}.${fname} = ${fname}"
        fi
    }

    echo "${gsf_script_indent}DELETE"
    echo "${gsf_script_indent}  FROM ${prefix} USING ${GF_TNAME} AS ${prefix}"
    echo -n "${GSF_WHERE_LINE}"
    lambda_count=0
    gsf_callback_prefs_rows "lambda_where"
    echo ";"
}

gsf_sql_import_table()
{
    local prefix="t"
    local -i lambda_count=0

    local param_format="${gsf_script_indent}%-${MAX_NAME_LEN}s %s,\n"

    lambda_fields()
    {
        if CB_ROW_IS_PARAM; then
            printf ${param_format} "${CALLBACK_ROW[0]}" "${CALLBACK_ROW[1]}"
        fi
    }

    echo "CREATE TABLE IF NOT EXISTS ${QT_NAME}"
    echo "("
    printf "${gsf_script_indent}%-${max_name_len}s INT UNSIGNED,\n" "${ID_FIELD_NAME}"
    gsf_callback_prefs_rows "lambda_fields"
    echo "${gsf_script_indent}INDEX(${ID_FIELD_NAME})"
    echo ");"
    echo
    echo "GRANT INSERT ON ${QT_NAME} TO 'webuser'@'localhost';"
    echo "GRANT FILE ON *.* to 'webuser'@'localhost';"
}

gsf_sql_import_proc_review()
{
    local proc_name="${IMPORT_PROC_ROOT}Review"

    local -i lambda_count=0
    lambda_selects()
    {
        if CB_ROW_IS_PARAM; then
            if [ $(( lambda_count++ )) -gt 0 ]; then
                echo ","
                echo  -n "${GSF_SELECT_SPACES}"
            fi
            echo -n "${CALLBACK_ROW[0]}"
        fi
    }

    echo "DROP PROCEDURE IF EXISTS ${proc_name} \$\$"
    echo "CREATE PROCEDURE ${proc_name}()"
    echo "BEGIN"
    echo -n "${GSF_SELECT_LINE}"
    gsf_callback_prefs_rows "lambda_selects"
    echo
    echo "${GSF_FROM_LINE}${QT_NAME}"
    echo "${GSF_WHERE_LINE}id_session = @session_confirmed_id;"
    echo "END \$\$"
}

gsf_sql_import_proc_abandon()
{
    local proc_name="${IMPORT_PROC_ROOT}Abandon"
    echo "DROP PROCEDURE IF EXISTS ${proc_name} \$\$"
    echo "CREATE PROCEDURE ${proc_name}()"
    echo "BEGIN"
    echo "${gsf_script_indent}DELETE"
    echo "${gsf_script_indent}  FROM ${GT_NAME}"
    echo "${GSF_WHERE_LINE}id_session = @session_confirmed_id;"
    echo "END \$\$"
}

gsf_sql_import_proc_accept()
{
    local -i lambda_count=0
    local ispaces

    lambda_values()
    {
        if CB_ROW_IS_PARAM; then
            local fname="${CALLBACK_ROW[0]}"
            if [ $(( lambda_count++ )) -gt 0 ]; then
                echo ", "
                echo -n "${ispaces}"
            fi
            echo -n "${fname}"
        fi
    }

    local proc_name="${IMPORT_PROC_ROOT}Accept"

    echo "DROP PROCEDURE IF EXISTS ${proc_name} \$\$"
    echo "CREATE PROCEDURE ${proc_name}()"
    echo "BEGIN"
    echo "${gsf_script_indent}INSERT INTO ${GF_TNAME}"

    lambda_count=0
    echo -n "${GSF_UPDATE_FIELDS_LINE}"
    ispaces="${GSF_UPDATE_SPACES_LINE}"
    gsf_callback_prefs_rows "lambda_values"
    echo ")"

    lambda_count=0
    echo -n "${GSF_SELECT_LINE}"
    ispaces="${GSF_SELECT_SPACES}"
    gsf_callback_prefs_rows "lambda_values"
    echo
    echo "${GSF_FROM_LINE}${QT_NAME}"
    echo "${GSF_WHERE_LINE}id_session = @session_confirmed_id;"
    echo
    echo "${gsf_script_indent}CALL ${IMPORT_PROC_ROOT}Abandon();"

    echo "END \$\$"
}
