.TH gensfw_srm 1 "March 2019"

.SH NAME
gensfw_srm \- Modify an SRM file through command line arguments

.SH SYNOPSIS
Yet to be entered

.SH DESCRIPTION
.B gensfw_srm
is a tool for making changes to an SRM file.  Lines and branchs within the
SRM file can be deleted or added with various options.  The location that these
actions take place are determined by selecting an existing line in the SRM file
by use of a rudimentary XPATH-like selection syntax.

.SH OPTIONS
.TP
.BR "--help" ", " "-h"
Show help options.  This command is self-documenting, so the most current
documentation will be found by using the \fBhelp\fI option and following the
instructions therein.

.SH EXAMPLES
Yet to be entered

.SH AUTHOR
Charles P. Jungmann

.SH SEE ALSO
gensfw(1)
gensfw_isotable_procs(1)
gensfw_proc_from_table(1)
