.TH gensfw_srm_from_proc 1 "March 2019"

.SH NAME
gensfw_srm_from_proc \- Generate a SRM reponse mode from a procedure

.SH SYNOPSIS
.B gensfw_srm_from_proc
.IR "database-name" " " "procedure-name" " [" "mode-name" ]
.SH DESCRIPTION
.B gensfw_srm_from_proc
is a tool for creating a response mode from a procedure.  Call with
.IR DATABASE " and " TABLE
names at a minimum, the response mode will be created with a schema that
includes field lines for each of the procedures parameters.  This somewhat
eases the task of matching the field name, and the resulting response mode
can then be modified by use of the
.B gensfw_srm
application.

.SH OPTIONS
.TP
.IB "[" mode-name "]"
.br
Label the output response modes according to the mode-name.  If the
mode-name is /fBlogin\fR, two response modes will be created,
.B login
and
.B login_submit


.SH EXAMPLES
Create a login interaction using procedure
.I App_User_Login
from database
.I SFW_Enroll.
.br
.B gensfw_srm_from_proc
.I SFW_Enroll App_User_Login login
.br

.SH AUTHOR
Charles P. Jungmann

.SH SEE ALSO
gensfw(1)
gensfw_srm(1)
gensfw_isotable_procs(1)
gensfw_proc_from_table(1)
