.TH gensfw 1 "25 July 2018"
.SH NAME
gensfw \- Generate Schema Framework Files
.SH SYNOPSIS
\fBgensfw\fR [\fIOptions\fR] [\fIgsf file name|stem\fR]
.SH DESCRIPTION
\fBgensfw\fR is an aid for writing SQL and SRM scripts in support of
web applications delivered using the Schema Framework.  In particular, the
generated SQL scripts will create procedures with parameters and results
whose data types and names match the fields in the target table.

The resulting scripts can be used directly under many circumstances, but may
also serve as an illustration of what are currently considered best practices.

Changes to default settings can be preserved in a special \fBgsf\fR file
that can be re-opened and changed as needed before generating new scripts.

The documentation for using \fBgensfw\fR is found in the \fIinfo gensfw\fR
pages.
.SH OPTIONS
.TP
\fB\-d \fI"Database Name"\fR
Open the named database.

.TP
\fB\-t \fI"Table Name"\fR
Open the named table.  Results in error if table not in named database.

.TP
\fB\-g \fI"GSF file name"\fR
Open the named gsf file.  If the file extension is omitted, an extension
of \fI.gsf\fR will be assumed.

.TP
\fB\-c \fICommand\fR
This option runs \fBgensfw\fR in batch mode.

For now, the only honored value for \fICommand\fR is \fBsave\fR,
which writes SRM and SQL code to files with file extensions matching
the content they hold.
.SH EXAMPLES
.TP
.B gensfw
.br
Open with the list of databases in localhost.
.TP
.BI "gensfw -d" " database"
.br
Open with the list of tables in database \fIdatabase\fR.
.br
.TP
.BI "gensfw -d" " database " -t " table"
.br
Open with the interaction editor for table \fItable\fR in database \fIdatabase\fR.
.br
.TP
.BI "gensfw -g" " Person.gsf"
.BI "gensfw" " Person.gsf"
.BI "gensfw" " Person"
.br
Assuming that \fIPerson.gsf\fR exists where \fBgensfw\fR is called, these
three examples will all open \fIPerson.gsf\fR.  The settings in place when
the file was saved are restored.
.br
.TP
.BI "gensfw" " Person " -c " save"
Opens \fIPerson.gsf\fR and executes the \fIsave\fR command to write the SQL
and SRM files.
.br

.SH AUTHOR
Charles P. Jungmann
.SH SEE ALSO
gensfw_isotable_procs(1)
.br
.B info gensfw
